import { useState } from "react";
import { useNavigate } from "react-router-dom";

import { setupMfa, verifyMfaSetup } from "../services/authServices";

const MfaSetup = () => {
  const navigate = useNavigate();

  const [qrCode, setQrCode] = useState("");
  const [token, setToken] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  const handleSetup = async () => {
    try {
      setLoading(true);
      setError("");

      const data = await setupMfa();

      setQrCode(data.qrCode);
    } catch (error) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async (e) => {
    e.preventDefault();

    if (token.length !== 6) {
      setError("Please enter the 6-digit code.");
      return;
    }

    try {
      setLoading(true);
      setError("");

      const data = await verifyMfaSetup(token);

      setMessage(data.message);

      setTimeout(() => {
        navigate("/profile");
      }, 1000);
    } catch (error) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-vh-100 bg-light d-flex align-items-center justify-content-center p-3">
      <div
        className="card border-0 shadow-lg rounded-4"
        style={{ maxWidth: "500px", width: "100%" }}
      >
        <div className="card-body p-4 p-md-5 text-center">
          <h2 className="fw-bold mb-2">Authenticator App</h2>

          <p className="text-muted">
            Add an extra layer of security to your account.
          </p>

          {!qrCode && (
            <button
              type="button"
              className="btn btn-dark w-100 mt-3"
              onClick={handleSetup}
              disabled={loading}
            >
              {loading ? "Generating..." : "Set Up Authenticator"}
            </button>
          )}

          {qrCode && (
            <>
              <p className="mt-4 mb-3">
                Scan this QR code using your authenticator app.
              </p>

              <img
                src={qrCode}
                alt="MFA QR Code"
                className="img-fluid mb-4"
                style={{ maxWidth: "220px" }}
              />

              <p className="text-muted small">
                After scanning, enter the 6-digit code generated by the app.
              </p>

              <form onSubmit={handleVerify}>
                <input
                  type="text"
                  inputMode="numeric"
                  maxLength={6}
                  className={`form-control form-control-lg text-center ${
                    error ? "is-invalid" : ""
                  }`}
                  placeholder="000000"
                  value={token}
                  onChange={(e) => {
                    const value = e.target.value.replace(/\D/g, "");

                    setToken(value);
                    setError("");
                  }}
                  style={{
                    letterSpacing: "8px",
                    fontWeight: "bold",
                  }}
                />

                {error && (
                  <div className="invalid-feedback text-start">{error}</div>
                )}

                {message && (
                  <div className="alert alert-success mt-3">{message}</div>
                )}

                <button
                  type="submit"
                  className="btn btn-dark btn-lg w-100 mt-3"
                  disabled={loading || token.length !== 6}
                >
                  {loading ? "Verifying..." : "Enable MFA"}
                </button>
              </form>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default MfaSetup;
