import express from "express";

import protect from "../middleware/authMiddleware/authMiddleware.js";

import {
  setupMfa,
  verifyMfaSetup,
  disableMfa,
} from "../controllers/mfaController/mfaController.js";

const router = express.Router();

/**
 * @swagger
 * /api/auth/mfa/setup:
 *   post:
 *     summary: Start MFA setup
 *     description: Generates an MFA secret and QR code for the authenticated user to scan with an authenticator app.
 *     tags:
 *       - MFA
 *     responses:
 *       200:
 *         description: MFA setup started successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 qrCode:
 *                   type: string
 *                   example: "data:image/png;base64,..."
 *       400:
 *         description: MFA is already enabled
 *       401:
 *         description: User is not authenticated
 *       404:
 *         description: User not found
 */
router.post("/setup", protect, setupMfa);

/**
 * @swagger
 * /api/auth/mfa/verify:
 *   post:
 *     summary: Verify MFA setup
 *     description: Verifies the 6-digit code generated by the authenticator app and enables MFA for the authenticated user.
 *     tags:
 *       - MFA
 *     security:
 *       - cookieAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - token
 *             properties:
 *               token:
 *                 type: string
 *                 description: 6-digit code generated by the authenticator app
 *                 example: "123456"
 *     responses:
 *       200:
 *         description: MFA enabled successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: "MFA enabled successfully."
 *       400:
 *         description: Invalid authenticator code or MFA setup has not been started
 *       401:
 *         description: User is not authenticated
 *       404:
 *         description: User not found
 */
router.post("/verify", protect, verifyMfaSetup);

/**
 * @swagger
 * /api/auth/mfa/disable:
 *   post:
 *     summary: Disable MFA
 *     description: Disables multi-factor authentication for the authenticated user and removes the stored MFA secret.
 *     tags:
 *       - MFA
 *     responses:
 *       200:
 *         description: MFA disabled successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: "MFA disabled successfully."
 *       401:
 *         description: User is not authenticated
 *       404:
 *         description: User not found
 */
router.post("/disable", protect, disableMfa);

export default router;