import { useEffect, useRef } from "react";
import socket from "../../../services/socket";
// useRef is used to store WebRTC objects without causing React re-renders.
// WebRTC uses this configuration when creating a connection.
// iceServers is empty for now because STUN/TURN has not been added yet.
const rtcConfig = {
  iceServers: [],
};

// This custom hook contains all WebRTC audio-call logic.
const useWebRTC = ({ currentUser, otherUserId, isCaller, callAccepted }) => {
  // Stores the WebRTC connection.
  // We use useRef because the same connection must be kept between renders.
  const peerConnectionRef = useRef(null);

  // Stores the current user's microphone stream.
  // We need this stream to send our voice to the other user.
  const localStreamRef = useRef(null);

  // Stores ICE candidates that arrive before the WebRTC connection is ready.
  // These candidates are added later when the remote description is available.
  const pendingCandidatesRef = useRef([]);

  // Gets access to the current user's microphone.
  // This function is used when we create the WebRTC connection.
  const getLocalStream = async () => {
    // If we already have the microphone stream,
    // return it instead of asking for microphone permission again.
    if (localStreamRef.current) {
      return localStreamRef.current;
    }

    try {
      // Ask the browser for microphone access.
      // We only need audio because this is an audio call.
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: true,
      });

      // Save the microphone stream.
      // This allows us to use the same stream again during the call.
      localStreamRef.current = stream;

      // Return the microphone stream to the caller.
      return stream;
    } catch (error) {
      // This happens if the browser cannot access the microphone
      // or the user does not give microphone permission.
      console.error("Microphone access error:", error);

      // Return null because we could not get the microphone.
      return null;
    }
  };

  // Creates the WebRTC connection between the two users.
  // This function is used by both the caller and receiver.
  const createPeerConnection = async () => {
    // If a WebRTC connection already exists,
    // return the existing connection instead of creating another one.
    if (peerConnectionRef.current) {
      return peerConnectionRef.current;
    }

    // Create a new WebRTC connection using our configuration.
    const peerConnection = new RTCPeerConnection(rtcConfig);

    // Save the connection so other functions can use the same connection.
    peerConnectionRef.current = peerConnection;

    // Get the current user's microphone.
    const localStream = await getLocalStream();

    // If microphone access was successful,
    // add the microphone tracks to the WebRTC connection.
    if (localStream) {
      // getTracks() gets the audio tracks from the microphone.
      // addTrack() tells WebRTC to send those tracks to the other user.
      localStream.getTracks().forEach((track) => {
        peerConnection.addTrack(track, localStream);
      });
    }

    // This event runs when audio from the other user reaches our browser.
    peerConnection.ontrack = (event) => {
      // Find the audio element from our React component.
      const remoteAudio = document.getElementById("remoteAudio");

      // Check that the audio element and remote stream exist.
      if (remoteAudio && event.streams[0]) {
        // Connect the other user's audio stream to the audio element.
        remoteAudio.srcObject = event.streams[0];

        // Start playing the other user's voice.
        // catch() prevents an error if the browser blocks autoplay.
        remoteAudio.play().catch(() => {});
      }
    };

    // This event runs when WebRTC finds a new ICE candidate.
    // ICE candidates help WebRTC find a network path between both users.
    peerConnection.onicecandidate = (event) => {
      // If there is no candidate, there is nothing to send.
      if (!event.candidate) return;

      // Send the ICE candidate through Socket.IO.
      // Socket.IO is only used for signaling.
      // The actual audio is sent through WebRTC.
      socket.emit("ice-candidate", {
        // ID of the user who generated the candidate.
        senderId: currentUser._id,

        // ID of the user who should receive the candidate.
        receiverId: otherUserId,

        // The network information generated by WebRTC.
        candidate: event.candidate,
      });
    };

    // Return the connection so other functions can use it.
    return peerConnection;
  };

  // Adds ICE candidates that arrived before the connection was ready.
  // This is used after the remote description has been set.
  const addPendingCandidates = async (peerConnection) => {
    // Go through every ICE candidate that was saved earlier.
    for (const candidate of pendingCandidatesRef.current) {
      // Add the saved candidate to the WebRTC connection.
      // RTCIceCandidate converts the received data into a WebRTC candidate.
      await peerConnection.addIceCandidate(new RTCIceCandidate(candidate));
    }

    // Clear the old candidates because they have already been added.
    pendingCandidatesRef.current = [];
  };

  // This function is used by the caller.
  // The caller creates an offer to start the WebRTC connection.
  const createOffer = async () => {
    try {
      // Get the existing WebRTC connection
      // or create a new one if it does not exist.
      const peerConnection = await createPeerConnection();

      // Create an offer containing the caller's WebRTC information.
      const offer = await peerConnection.createOffer();

      // Save the offer as our local description.
      // WebRTC needs this before sending the offer to the receiver.
      await peerConnection.setLocalDescription(offer);

      // Send the offer to the receiver using Socket.IO.
      socket.emit("offer", {
        // ID of the caller.
        senderId: currentUser._id,

        // ID of the person receiving the call.
        receiverId: otherUserId,

        // WebRTC offer information.
        offer,
      });
    } catch (error) {
      // Shows an error if creating or sending the offer fails.
      console.error("Create offer error:", error);
    }
  };

  // This function is used by the receiver.
  // It receives the caller's offer and creates an answer.
  const handleOffer = async (data) => {
    try {
      // Create the WebRTC connection if it does not already exist.
      const peerConnection = await createPeerConnection();

      // Save the caller's offer as the remote description.
      // This tells WebRTC what connection information the caller has.
      await peerConnection.setRemoteDescription(
        new RTCSessionDescription(data.offer),
      );

      // Add ICE candidates that arrived before the offer.
      await addPendingCandidates(peerConnection);

      // Create an answer for the caller's offer.
      const answer = await peerConnection.createAnswer();

      // Save the answer as our local description.
      // WebRTC needs this before sending the answer.
      await peerConnection.setLocalDescription(answer);

      // Send the answer back to the caller through Socket.IO.
      socket.emit("answer", {
        // ID of the receiver.
        senderId: currentUser._id,

        // Send the answer back to the caller.
        receiverId: data.senderId,

        // WebRTC answer information.
        answer,
      });
    } catch (error) {
      // Shows an error if the receiver cannot process the offer.
      console.error("Handle offer error:", error);
    }
  };

  // This function is used by the caller.
  // It receives the answer created by the receiver.
  const handleAnswer = async (data) => {
    try {
      // Get the WebRTC connection that the caller already created.
      const peerConnection = peerConnectionRef.current;

      // If the connection does not exist,
      // there is nothing to do with the answer.
      if (!peerConnection) return;

      // Save the receiver's answer as the remote description.
      // This completes the main offer/answer process.
      await peerConnection.setRemoteDescription(
        new RTCSessionDescription(data.answer),
      );

      // Add any ICE candidates that arrived before the answer.
      await addPendingCandidates(peerConnection);
    } catch (error) {
      // Shows an error if the answer cannot be processed.
      console.error("Handle answer error:", error);
    }
  };

  // This function handles ICE candidates received from the other user.
  // Both caller and receiver use this function.
  const handleIceCandidate = async (data) => {
    try {
      // Get our current WebRTC connection.
      const peerConnection = peerConnectionRef.current;

      // Sometimes an ICE candidate arrives before the remote description.
      // WebRTC cannot add it yet, so we save it for later.
      if (!peerConnection || !peerConnection.remoteDescription) {
        // Store the candidate until the connection is ready.
        pendingCandidatesRef.current.push(data.candidate);

        // Stop here because we cannot add the candidate yet.
        return;
      }

      // Add the received ICE candidate to our WebRTC connection.
      await peerConnection.addIceCandidate(new RTCIceCandidate(data.candidate));
    } catch (error) {
      // Shows an error if the ICE candidate cannot be added.
      console.error("ICE candidate error:", error);
    }
  };

  // This effect starts the WebRTC connection on the caller's side.
  // It runs when the call has been accepted.
  useEffect(() => {
    // We need all four values before creating the offer.
    if (currentUser?._id && otherUserId && isCaller && callAccepted) {
      // Start the WebRTC offer process.
      createOffer();
    }

    // Run this effect when any of these values change.
    // callAccepted is especially important because WebRTC starts after acceptance.
  }, [currentUser?._id, otherUserId, isCaller, callAccepted]);

  // This effect creates the Socket.IO listeners.
  // These listeners receive WebRTC signaling messages.
  useEffect(() => {
    // Do not create listeners until we know the current user's ID.
    if (!currentUser?._id) return;

    // Receiver listens for the caller's offer.
    socket.on("offer", handleOffer);

    // Caller listens for the receiver's answer.
    socket.on("answer", handleAnswer);

    // Both users listen for ICE candidates.
    socket.on("ice-candidate", handleIceCandidate);

    // Remove the listeners when this hook is removed or recreated.
    // This prevents duplicate Socket.IO listeners.
    return () => {
      // Remove the offer listener.
      socket.off("offer", handleOffer);

      // Remove the answer listener.
      socket.off("answer", handleAnswer);

      // Remove the ICE candidate listener.
      socket.off("ice-candidate", handleIceCandidate);
    };

    // Recreate the listeners when the current user or other user changes.
  }, [currentUser?._id, otherUserId]);

  // Ends the current WebRTC call.
  // This function should be called when either user ends the call.
  const endWebRTC = () => {
    // Close the WebRTC connection if it exists.
    peerConnectionRef.current?.close();

    // Remove the old connection.
    // This allows a new connection to be created for the next call.
    peerConnectionRef.current = null;

    // Get all microphone tracks and stop them.
    // This turns off microphone access after the call ends.
    localStreamRef.current?.getTracks().forEach((track) => {
      track.stop();
    });

    // Remove the old microphone stream.
    // The next call will create a new stream.
    localStreamRef.current = null;

    // Remove any ICE candidates left from the previous call.
    // This prevents old candidates from being used in a new call.
    pendingCandidatesRef.current = [];
  };

  // Return the functions that other components need.
  // For example, the call component can use endWebRTC() when the call ends.
  return {
    createPeerConnection,
    getLocalStream,
    endWebRTC,
  };
};

// Export the hook so it can be imported into the call components.
export default useWebRTC;
